"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Monster = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var monster_js_1 = require("./my-game/monster.js");
Object.defineProperty(exports, "Monster", { enumerable: true, get: function () { return monster_js_1.Monster; } });
