"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TurtleStatus = exports.ControlCommand = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var control_command_js_1 = require("./turtle-sim/control-command.js");
Object.defineProperty(exports, "ControlCommand", { enumerable: true, get: function () { return control_command_js_1.ControlCommand; } });
var turtle_status_js_1 = require("./turtle-sim/turtle-status.js");
Object.defineProperty(exports, "TurtleStatus", { enumerable: true, get: function () { return turtle_status_js_1.TurtleStatus; } });
